-- MySQL Script generated by MySQL Workbench
-- lun 20 may 2019 20:12:26 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bbddProyecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bbddProyecto
-- -----------------------------------------------------
drop schema if exists `bbddProyecto`;
CREATE SCHEMA IF NOT EXISTS `bbddProyecto` DEFAULT CHARACTER SET utf8 ;
USE `bbddProyecto`;

DROP USER IF EXISTS 'amonfortp1'@'%';
CREATE USER 'amonfortp1'@'%';
GRANT ALL PRIVILEGES ON bbddProyecto.* TO 'amonfortp1'@'%' IDENTIFIED BY '1111';
GRANT all PRIVILEGES on mysql.proc TO 'amonfortp1'@'%' IDENTIFIED BY '1111';

-- -----------------------------------------------------
-- Table `bbddProyecto`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbddProyecto`.`Alumno` (
  `email` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45),
  `password` BLOB NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bbddProyecto`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbddProyecto`.`Curso` (
  `curso` YEAR NOT NULL,
  PRIMARY KEY (`curso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bbddProyecto`.`Mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbddProyecto`.`Mensaje` (
  `tipo` VARCHAR(45) NOT NULL,
  `mensaje` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bbddProyecto`.`Periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbddProyecto`.`Periodo` (
  `idPeriodo` INT(11) NOT NULL AUTO_INCREMENT,
  `diaInicio` DATE NOT NULL,
  `diaFinal` DATE NOT NULL,
  `horaInicio` TIME NOT NULL,
  `horaFinal` TIME NOT NULL,
  `tiempo` TIME NOT NULL,
  `curso` YEAR NOT NULL,
  `habilitado` TINYINT(1) NOT NULL DEFAULT TRUE,
  PRIMARY KEY (`idPeriodo`),
  UNIQUE INDEX `diaInicio` (`diaInicio` ASC, `diaFinal` ASC, `horaInicio` ASC, `horaFinal` ASC, `curso` ASC),
  INDEX `fk_Periodo_1_idx` (`curso` ASC),
  CONSTRAINT `fk_Periodo_1`
    FOREIGN KEY (`curso`)
    REFERENCES `bbddProyecto`.`Curso` (`curso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bbddProyecto`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbddProyecto`.`Reserva` (
  `dia` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `idPeriodo` INT(11) NOT NULL,
  PRIMARY KEY (`dia`, `hora`),
  UNIQUE INDEX `dia` (`dia` ASC, `hora` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_Reserva_1_idx` (`idPeriodo` ASC),
  INDEX `fk_Reserva_2_idx` (`email` ASC),
  CONSTRAINT `fk_Reserva_1`
    FOREIGN KEY (`idPeriodo`)
    REFERENCES `bbddProyecto`.`Periodo` (`idPeriodo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Reserva_2`
    FOREIGN KEY (`email`)
    REFERENCES `bbddProyecto`.`Alumno` (`email`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `bbddProyecto` ;

-- -----------------------------------------------------
-- procedure
-- -----------------------------------------------------

/*
DELIMITER @@
DROP PROCEDURE IF EXISTS crearAlumno @@
CREATE PROCEDURE crearAlumno(in email VARCHAR(45), in nombre VARCHAR(45), in apellidos VARCHAR(45), OUT login VARCHAR(45), OUT passw VARCHAR(45))
BEGIN

	DECLARE l VARCHAR(45);
    DECLARE p VARCHAR(45);

	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		SHOW ERRORS LIMIT 1;      
		RESIGNAL;   
		ROLLBACK;
	END;
		
	START TRANSACTION;
		
        
		INSERT INTO Alumno VALUES (email, nombre, apellidos, l, p);

	COMMIT;
	
END@@

DELIMITER ;
*/


DELIMITER @@
DROP PROCEDURE IF EXISTS anularReserva @@
CREATE PROCEDURE anularReserva(in correo VARCHAR(45))
BEGIN

	DECLARE diaR DATE;
    DECLARE horaR TIME;
    
    

	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		SHOW ERRORS LIMIT 1;      
		RESIGNAL;   
		ROLLBACK;
	END;
	
SELECT 
    dia, hora
INTO diaR , horaR FROM
    Reserva
WHERE
    email = correo;
    
	IF diaR = null
	THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'No tienes ninguna reserva', MYSQL_ERRNO = 1001;
	END IF;
	IF current_date() > adddate(diaR, interval 1 day)
	THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'No se puede eliminar la reserva cuando quedan menos de 24h para el dia', MYSQL_ERRNO = 1002;
	END IF;
        
	START TRANSACTION;
		
		UPDATE Reserva 
		SET 
			email = NULL
		WHERE
			dia = diaR AND hora = horaR;
        
	COMMIT;
	
END@@

DELIMITER ;



DELIMITER @@
DROP PROCEDURE IF EXISTS reservar @@
CREATE PROCEDURE reservar(in correo varchar(45), in diaR DATE, in horaR TIME)
BEGIN

	DECLARE exiteReservaUsuario INT DEFAULT 0;
    DECLARE existeReserva INT;
    DECLARE yaReservado INT;
    DECLARE DATOS VARCHAR(45);
    

	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		SHOW ERRORS LIMIT 1;      
		RESIGNAL;   
		ROLLBACK;
	END;
		
	SET DATOS = concat(DATE_FORMAT(diaR, '%d %m %Y'),TIME_FORMAT(horaR, "%H %i %s"));
	SELECT 	COUNT(dia)
	INTO exiteReservaUsuario FROM Reserva
	WHERE email = correo;
        
	SELECT 	count(dia)
	INTO existeReserva FROM	Reserva
	WHERE dia = diaR AND hora = horaR;
		
	SELECT count(*) 
    INTO yaReservado FROM Reserva 
    WHERE email IS NOT NULL;
    
	IF exiteReservaUsuario = 1
	THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'El usuario ya tiene una reserva', MYSQL_ERRNO = 1001;
	ELSEIF existeReserva = 0
    THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = DATOS, MYSQL_ERRNO = 1002;
    ELSEIF yaReservado = 1
	THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'Ya hay una reserva ese dia', MYSQL_ERRNO = 1003;
	ELSE
		UPDATE Reserva 
		SET 
			email = correo
		WHERE
			dia = diaR AND hora = horaR;
	
	END IF;
END@@

DELIMITER ;


DELIMITER @@
DROP PROCEDURE IF EXISTS crearPeriodo @@
CREATE PROCEDURE crearPeriodo(in diaInicio DATE, in diaFinal DATE, in horaInicio TIME, in horaFinal TIME, in tiempo TIME, in idCurso YEAR)
BEGIN
  
	DECLARE id INT;

	DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
      SHOW ERRORS LIMIT 1;      
      RESIGNAL;   
      ROLLBACK;
    END;
    
SELECT 
    IFNULL(MAX(idPeriodo), 0) + 1
INTO id FROM
    Periodo;
		
	IF diaInicio > diaFinal
	THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'El dia inicial no puede ser mayor que el dia final', MYSQL_ERRNO = 1001;
	END IF; 
    IF horaInicio > horaFinal
    THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'El hora inicial no puede ser mayor que la hora final', MYSQL_ERRNO = 1002;
	END IF; 
    IF diaInicio < Adddate(current_date(), INTERVAL 1 DAY)
    THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'El dia y la hora inicial no puede ser menor que el actual', MYSQL_ERRNO = 1003;
	END IF; 
    IF tiempo <= '00:05:00'
    THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'El tiempo debe ser mayor o igual a 5 minutos', MYSQL_ERRNO = 1005;
	END IF; 
    IF idCurso < year(current_date())
    THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'El curso no puede ser anterior al actual', MYSQL_ERRNO = 1006;
    END IF; 
		
	START TRANSACTION;

		INSERT INTO Periodo (idPeriodo,diaInicio, diaFinal, horaInicio, horaFinal, tiempo, curso) VALUES (id,diaInicio, diaFinal, horaInicio, horaFinal, tiempo, idCurso);
		
		CALL crearReservas(id);           

	COMMIT;
	
END@@

DELIMITER ;

DELIMITER @@
DROP PROCEDURE IF EXISTS crearReservas @@
CREATE PROCEDURE crearReservas(in id INT)
BEGIN


	-- DECLARO VARIABLES
    DECLARE existePeriodo INT DEFAULT 0;
    DECLARE diaAux DATE;
    DECLARE diaFin DATE;
    DECLARE horaIni TIME;
    DECLARE horaFin TIME;
    DECLARE temp TIME;
    
    DECLARE horaAux TIME;
    
	-- SELECT PARA DAR VALOR A LAS VARIABLES
SELECT 
    COUNT(idPeriodo),
    diaInicio,
    diaFinal,
    horaInicio,
    horaFinal,
    tiempo
INTO existePeriodo , diaAux , diaFin , horaIni , horaFin , temp FROM
    Periodo
WHERE
    idPeriodo = id;

	SET horaAux = horaIni;
		
	IF existePeriodo = 1
	THEN

		dia: LOOP
			IF DAYOFWEEK(diaAux) = 1
			THEN
				SET diaAux = ADDDATE(diaAux, INTERVAL 1 DAY);
			ELSEIF DAYOFWEEK(diaAux) = 7
			THEN
				SET diaAux = ADDDATE(diaAux, INTERVAL 2 DAY);
			ELSE
				IF diaAux <= diaFin
				THEN
					hora: LOOP
						IF horaAux <= horaFin
						THEN
							INSERT INTO Reserva (dia,hora,idPeriodo) VALUES(diaAux,horaAux,id);
							SET horaAux = ADDTIME(horaAux, temp);
							ITERATE hora;
						ELSE
							LEAVE hora;
						END IF;
					END LOOP hora;
					SET horaAux = horaIni;
					SET diaAux = ADDDATE(diaAux,INTERVAL 1 DAY);
					ITERATE dia;
				ELSE
					LEAVE dia;
				END IF;
            END IF;
		END LOOP dia;
	END IF;
END@@

DELIMITER ;

INSERT INTO Curso VALUES (2019);

CALL crearPeriodo('2019-07-01', '2019-07-15', '12:00:00', '15:00:00', '00:30:00', 2019);

INSERT INTO Alumno VALUES ('amonfortp1@ieslavereda.es', 'Alejandro', 'Monfort', 'Parra', PASSWORD('1111'));
INSERT INTO Alumno VALUES ('amonfortparra@gmail.com', 'Alex', 'Monfort', 'Parra', PASSWORD('1111'));

INSERT INTO Mensaje VALUES ('mensajeUsuarioCreado', 'Su usuario se a creado correctemente, su login y contraseña son: ');
INSERT INTO Mensaje VALUES ('mensajeReservado', 'En este documento se explicara todos los documentos que se debe traer el dia de la reserva.');
INSERT INTO Mensaje VALUES ('mensajeReservadoAnulado', 'Se a eliminado su reserva del dia: ');

CALL reservar('amonfortparra@gmail.com', '2019-07-01', '12:30:00');
-- CALL anularReserva('amonfortparra@gmail.com');